### ISSUE TITLE
device_state.g.dart:13:17: Error: Method not found

### ISSUE THREAD

**Issue by a43mrk** [tim-smart/dart_emulators#10]
`../../../.pub-cache/hosted/pub.dartlang.org/emulators-0.4.9/lib/src/device/device_state.g.dart:13:17: Error: Method not found: '$enumDecode'.
      platform: $enumDecode(_$DevicePlatformEnumMap, json['platform']),`

Is some kind of code generation required?
I tryed to run the tools.dart and got the error above :( can you help.

**Comment by tim-smart** [comment]
No code generation is needed. That file is already generated for you :)

That function is from `json_annotation`. I have updated the json_annotation version constraint to see if it fixes this.
If you try the `main` branch in your dev dependencies, see if that changes anything:

```yaml
  emulators:
    git:
      url: https://github.com/tim-smart/dart_emulators.git
      ref: main
```
