### ISSUE TITLE
emu.forEach not working

### ISSUE THREAD

**Issue by intervall-peter** [tim-smart/dart_emulators#21]
I'm trying to automate screenshot generation for a hobby project. 

I have the following `emulator_runner.dart` file located in a directory called `test_driver`:

```dart
import 'package:emulators/emulators.dart';

Future<void> main() async {
  List<String> emulatorIds = [
    'Pixel_6_API_33_1',
    // 'iPhone 14 Pro',
  ];
  print('Running process');
  await runFlutterScreenshotTests(emulatorIds);
}

Future<void> runFlutterScreenshotTests(List<String> emulatorIds) async {
  final emulators = await Emulators.build();

  // Shutdown all the running emulators
  await emulators.shutdownAll();

  print('Emulators: $emulators');
  final configs = [
    {'locale': 'en-US'},
  ];
  print('Running forEach');
  await emulators.forEach(emulatorIds)((device) async {
    print('running device $device');
    for (final _ in configs) {
      DeviceState state = device.state;
      print('Running emulator ${state.name} with id ${state.id}');
    }
  });
}
```

When I run this using `dart test_driver/emulator_runner.dart` I get the following output: 
```
Running process
Emulators: Instance of 'Emulators'
Running forEach
```

And after a few minutes the process ends with
```
level=INFO time="2023-08-06T17:18:00.010053" message="Interrupted()"
```

When I run with `iPhone 14 Pro` instead of `Pixel_6_API_33_1`, I get the following error after a few seconds:
```
level=INFO time="2023-08-06T17:19:58.977096" message="Defect(type '(Object?) => ZIO<NoEnv, FlutterError, Unit>' is not a subtype of type '(Cause<FlutterError>) => ZIO<Never, FlutterError, Unit>' of 'f')
 Stack: #0      ZIO.tapErrorCause (package:elemental/src/zio.dart)
#1      ZIO.traverseIterablePar.<anonymous closure>.<anonymous closure> (package:elemental/src/zio.dart:417:18)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162:27)
#5      new _List.of (dart:core-patch/array.dart:127:20)
#6      new List.of (dart:core-patch/array_patch.dart:49:20)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      ZIO.traverseIterablePar.<anonymous closure> (package:elemental/src/zio.dart:420:14)
#9      ZIO.unsafeRun (package:elemental/src/zio.dart:87:24)
#10     ZIO.map.<anonymous closure> (package:elemental/src/zio.dart:710:25)
#11     ZIO.unsafeRun (package:elemental/src/zio.dart:87:24)
#12     ZIOAskExt.ask.<anonymous closure> (package:elemental/src/zio.dart:1075:46)
#13     ZIO.unsafeRun (package:elemental/src/zio.dart:87:24)
#14     ZIO.map.<anonymous closure> (package:elemental/src/zio.dart:710:25)
#15     ZIO.unsafeRun (package:elemental/src/zio.dart:87:24)
#16     ZIO.flatMap.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:elemental/src/zio.dart:592:25)
#17     Right.match (package:fpdart/src/either.dart:526:14)
#18     ZIO.flatMap.<anonymous closure>.<anonymous closure> (package:elemental/src/zio.dart:590:22)
<asynchronous suspension>
)"
```

After a few minutes the process ends without any more output. 

I'm using Flutter 3.10.6 and Dart 3.0.6. 

This is my `pubspec.yaml`:

```yml
name: scorecard
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6
  path: ^1.8.3
  linked_scroll_controller: ^0.2.0
  custom_refresh_indicator: ^2.0.1
  package_info_plus: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  emulators: ^0.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icon.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

I just started learning flutter a few weeks ago, so I might have missed some setup steps. The emulators both work fine when running my app during development.

Did I miss any setup steps somewhere?
